apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: auth
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
  data:
  - secretKey: postgresql-postgres-password
    remoteRef:
      key: kube/authentik
      property: postgresql_password
  - secretKey: postgresql-password
    remoteRef:
      key: kube/authentik
      property: postgresql_password
  - secretKey: secret_key
    remoteRef:
      key: kube/authentik
      property: secret_key
