apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: curseforge-api-key
  namespace: games
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: curseforge-api-key
  data:
  - secretKey: apikey
    remoteRef:
      key: kube/minecraft
      property: curseforge_api_key
