# Application 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rescue
  labels:
    app: rescue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rescue
  template:
    metadata:
      labels:
        app: rescue
    spec:
      containers:
      - name: rescue
        image: raesene/alpine-containertools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rescue1
  labels:
    app: rescue1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rescue1
  template:
    metadata:
      labels:
        app: rescue1
    spec:
      containers:
      - name: rescue1
        image: raesene/alpine-containertools
