# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-test
#   namespace: ingress-nginx
# spec:
#   selector:
#     matchLabels:
#       app: nginx-test
#   template:
#     metadata:
#       labels:
#         app: nginx-test
#     spec:
#       containers:
#       - name: httpd
#         image: httpd:2.4.53-alpine
#         ports:
#         - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: ingress-nginx
spec:
  selector:
    app: nginx-test
  ports:
  - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_method = "GET") {
        rewrite ^/$ https://test.new.juicecloud.org permanent;
      }
spec:
  ingressClassName: nginx
  rules:
  - host: test.services.juicecloud.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-test
            port:
              number: 80

