apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptimekuma
  namespace: applications
spec:
  serviceName: "uptimekuma"
  replicas: 1
  selector:
    matchLabels:
      app: uptimekuma
  template:
    metadata:
      labels:
        app: uptimekuma
    spec:
      containers:
      - name: uptimekuma
        image: louislam/uptime-kuma:1
        ports:
        - name: uptimekuma-web
          containerPort: 3001
          protocol: TCP
        volumeMounts:
        - name: uptimekuma-data
          mountPath: /app/data/
  volumeClaimTemplates:
  - metadata:
      name: uptimekuma-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: longhorn
      resources:
        requests:
          storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: uptimekuma
  namespace: applications
  labels:
    app: uptimekuma
spec:
  selector:
    app: uptimekuma
  ports:
  - port: 3001
    name: uptimekuma-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptimekuma
  namespace: applications
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/auth-url: |-
      http://ak-outpost-authentik-embedded-outpost.auth.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    # If you're using domain-level auth, use the authentication URL instead of the application URL
    nginx.ingress.kubernetes.io/auth-signin: |-
      https://uptime.services.juicecloud.org/outpost.goauthentik.io/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - uptime.services.juicecloud.org
    secretName: uptimekuma-cert
  rules:
  - host: uptime.services.juicecloud.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uptimekuma
            port:
              number: 3001
