# v0.13.2
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-controller
  name: helm-controller
  namespace: helm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-controller
  template:
    metadata:
      labels:
        app: helm-controller
    spec:
      serviceAccountName: helm-controller-svc
      containers:
      - command:
        - helm-controller
        image: rancher/helm-controller:v0.13.2
        name: helm-controller
